### ISSUE TITLE
v1.2 TODO List

### ISSUE THREAD

**Issue by roccomuso** [roccomuso/iot-433mhz#29]
Tasks left for the v1.2 Release:

## Core

- [ ] Test 433utils and WiringPi on RPi.
- [ ] Backup feature Import/Export cards (#25).
- [ ] Embed a DDNS client, `no-ip`. (#32)

## Notifications

- [ ] Email notification (#18).

## Dev

- [ ] CI: tests (#28)
