### ISSUE TITLE
v1.1 TODO List

### ISSUE THREAD

**Issue by roccomuso** [roccomuso/iot-433mhz#3]
Once the TODO list is completed, we'll make a v1.1 release (#2).
## Core
- [x] Use SerialPort to communicate with Arduino.
- [x] Make adapter to expose one way to operate with HW layer.
- [x] Multiplatform test (Windows, RPi, Mac, Linux).
- [x] Socket.io integration.
- [x] Fixed version needed for the **package.json** dependencies.
- [x] Use 'nedb' for DB handling.
- [x] DB Compacting.
- [x] Real-time console-mirroring, (/console.html).
- [x] Console parameters parsing (yargs.js).
## UI
- [x] Add dependencies, Bootstrap, Bootstrap-material, jQuery, hover.css, notie.js etc..
- [x] Add Logo.
- [x] Add footer credits.
- [x] Add to Home Screen button for Mobile devices.
- [x] Web socket integration.
- [x] Handle incoming RF codes with snackbars.
- [x] Add Cards system based on 4 columns.
- [x] Ignore/Assign code button on snackbar.
- [x] Notification sound on initCards or codes received.
- [x] Switch sound.
- [x] Animated favicon (favico.js)
### Menu
- [x] Add Circular Menu.
- [x] Add Home Button.
- [x] Add Ignored Codes Page.
- [x] Add new Card Page.
- [x] Add About Page.
- [x] Add Settings Page. (#4)
### Cards
- [x] Implement **Info** Card type.
- [x] Implement **Switch** Card type.
- [x] Implement **Alarm** Card type #8 .
- [x] Add color background to the newCard form.
- [x] Cards filtering and re-ordering with MixItUp.
- [x] Handle Delete and Mute button in Dropdown menu.
### API
- [x] Implement <code>/api/settings/get</code>
- [x] Implement <code>/api/system/get/uid</code>
- [x] Implement <code>/api/system/new/uid</code>
- [x] Implement <code>/api/system/telegram/enable</code>
- [x] Implement <code>/api/system/telegram/disable</code>
- [x] Implement <code>/api/system/email/enable</code>
- [x] Implement <code>/api/system/email/disable</code>
- [x] Implement <code>/api/code/send/[code]</code>
- [x] Implement <code>/api/codes/ignored</code>
- [x] Implement <code>/api/codes/all</code>
- [x] Implement <code>/api/codes/available</code>
- [x] Implement <code>/api/cards/all</code>
- [x] Implement <code>/api/cards/get/[shortname]</code>
- [x] Implement POST- <code>/api/cards/new</code>
- [x] Implement <code>/api/cards/delete/[shortname]</code>
- [x] Implement <code>/api/switch/[shortname]/toggle</code> (just for **switch**)
- [x] Implement <code>/api/switch/[shortname]/on</code> (just for **switch**)
- [x] Implement <code>/api/switch/[shortname]/off</code> (just for **switch**)
- [x] Implement <code>/api/alarm/[shortname]/arm</code> (just for **alarm**)
- [x] Implement <code>/api/alarm/[shortname]/disarm</code> (just for **alarm**)
- [x] Implement <code>/api/webhook/get</code>
- [x] Implement <code>/api/webhook/get/[webHookShortname]</code>
- [x] Implement POST - <code>/api/webhook/add/[webHookShortname]</code>
- [x] Implement <code>/api/webhook/delete/[webHookShortname]</code>
- [x] Implement POST - <code>/api/webhook/delete/[webHookShortname]</code>
- [x] Implement POST - <code>/api/webhook/trigger/[webHookShortname]</code>
## Notifications
- [x] WebHooks.
- [x] Telegram Bot.
### Documentation
- [x] Update Web Interface image when alarm card will be completed.
- [x] Update Postman collection file in <code>/other</code> once API are done.
- [x] Fill Features section.
